debug: true

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:h2:mem:conf;MODE=mysql;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
    initialization-mode: always
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 20
      minimum-idle: 5

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false